version: '2'
volumes:
    resin-data:
services:
  influxdb:
    restart: always
    build: ./influxdb
    volumes:
      - 'resin-data:/data'
  grafana:
    restart: always
    build: ./grafana
    ports:
      - "80:3000"
    volumes:
      - 'resin-data:/data'
  cloud_connector:
    privileged: true
    build: ./cloud_connector
    restart: always
    ports:
      - "8080:8080"
    depends_on:
     - influxdb
  sense-hat-device:
    restart: always
    privileged: true
    build: ./sense-hat-device
    depends_on:
      - cloud_connector
  darsky-api-device:
    restart: always
    build: ./darksky-api-device
    depends_on:
    - cloud_connector
